apiVersion: v1
kind: Service
metadata:
  name: node-red-flight
  labels:
    app: node-red-flight
spec:
  selector:
    app: node-red-flight
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 1880
    targetPort: 1880